import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from 'sonner';
import "./globals.css";
import { Navbar } from '@/components/navbar';
import { AuthLayout } from '@/components/auth-layout';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Online Store",
  description: "Generated by create next app",
};

const publicPaths = ['/auth/login', '/auth/register'];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          geistSans.variable,
          geistMono.variable
        )}
      >
        <AuthLayout>
          <main>
            <Navbar />
            <div className="container mx-auto pt-5">
              {children}
            </div>
          </main>
          <Toaster position="top-right" />
        </AuthLayout>
      </body>
    </html>
  );
}